/**
 * Tamil overlay for the pest-zone screen. Keyed by the exact English source
 * string used in the component, matching the Hindi overlay's shape.
 * Translated faithfully from the English source; not yet reviewed by a native
 * speaker or an agronomist.
 */
export const pestZoneTamil: Record<string, string> = {
  "Do not repeat the same IRAC group or spray from old leaf damage alone.": "ஒரே IRAC குழுவை மீண்டும் பயன்படுத்த வேண்டாம்; பழைய இலைச் சேதத்தை மட்டும் வைத்துத் தெளிக்க வேண்டாம்.",
  "Rotate IRAC groups and treat new activity, not old deadhearts or whiteheads.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; பழைய காய்ந்த நடுத்தண்டுகளுக்கோ வெண்கதிர்களுக்கோ அல்ல, புதிய பூச்சி நடமாட்டத்திற்கே சிகிச்சை அளியுங்கள்.",
  "Rotate IRAC groups and avoid resurgence-causing calendar applications.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; பூச்சிகள் மீண்டும் பெருகச் செய்யும் நாட்காட்டி அடிப்படையிலான தெளிப்புகளைத் தவிர்க்கவும்.",
  "Rotate IRAC groups and confirm species because planthopper response differs.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; தத்துப்பூச்சிகளின் எதிர்வினை வேறுபடுவதால் இனத்தை உறுதிப்படுத்துங்கள்.",
  "Rotate IRAC groups and avoid calendar treatment.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; நாட்காட்டி அடிப்படையிலான சிகிச்சையைத் தவிர்க்கவும்.",
  "Rotate IRAC groups and do not treat old bored stems without fresh activity.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; புதிய பூச்சி நடமாட்டம் இல்லாமல் பழைய துளையிடப்பட்ட தண்டுகளுக்குச் சிகிச்சை அளிக்க வேண்டாம்.",
  "Rotate IRAC groups and avoid repeated use of one active ingredient.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; ஒரே செயல்படு பொருளை மீண்டும் மீண்டும் பயன்படுத்துவதைத் தவிர்க்கவும்.",
  "Rotate IRAC groups and preserve natural enemies.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; இயற்கை எதிரிப் பூச்சிகளைப் பாதுகாக்கவும்.",
  "Rotate IRAC groups and avoid repeated broad-spectrum sprays.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; பரந்த தாக்கமுள்ள தெளிப்புகளை மீண்டும் மீண்டும் செய்வதைத் தவிர்க்கவும்.",
  "Rotate IRAC groups and do not repeat ineffective applications against older larvae.": "IRAC குழுக்களை மாற்றி மாற்றிப் பயன்படுத்துங்கள்; வளர்ந்த புழுக்களுக்கு எதிராகப் பலனற்ற சிகிச்சைகளை மீண்டும் செய்ய வேண்டாம்.",
  "Pest map": "பூச்சி வரைபடம்",
  "Select a zone, check a photo, then open the zone for its plan and history.": "ஒரு மண்டலத்தைத் தேர்ந்தெடுத்து, படத்தைச் சரிபார்த்து, பிறகு அதன் திட்டத்தையும் வரலாற்றையும் காண மண்டலத்தைத் திறக்கவும்.",
  "Pest detector ready": "பூச்சி கண்டறிவான் தயார்",
  "Pest detector unavailable": "பூச்சி கண்டறிவான் கிடைக்கவில்லை",
  "Checking model…": "மாதிரி சரிபார்க்கப்படுகிறது…",
  "Check a plant": "ஒரு செடியைச் சரிபார்க்கவும்",
  "Take or choose a pest photo": "பூச்சிப் படத்தை எடுக்கவும் அல்லது தேர்ந்தெடுக்கவும்",
  "Tap to change photo": "படத்தை மாற்ற தட்டவும்",
  "Use one clear close-up. Include the insect and its damage where possible.": "ஒரு தெளிவான அருகிலான படத்தைப் பயன்படுத்தவும். முடிந்தால் பூச்சியையும் அதன் சேதத்தையும் சேர்க்கவும்.",
  "Field zone": "வயல் மண்டலம்",
  "Crop": "பயிர்",
  "Zone": "மண்டலம்",
  "Check this photo": "இந்தப் படத்தைச் சரிபார்",
  "Checking photo…": "படம் சரிபார்க்கப்படுகிறது…",
  "Same plants and similar photo distance as the previous test": "முந்தைய சோதனையின் அதே செடிகளும் ஏறக்குறைய அதே தொலைவும்",
  "Tick only for comparable photos. Otherwise no improvement claim is made.": "ஒப்பிடத்தக்க படங்களுக்கு மட்டுமே குறியிடவும். இல்லையெனில் முன்னேற்றம் குறித்த கூற்று எதுவும் செய்யப்படாது.",
  "Results save automatically to the selected zone.": "முடிவுகள் தேர்ந்தெடுக்கப்பட்ட மண்டலத்தில் தானாகவே சேமிக்கப்படும்.",
  "Farm Layout": "பண்ணை அமைப்பு",
  "Same farm zones · latest pest check": "அதே பண்ணை மண்டலங்கள் · சமீபத்திய பூச்சி சரிபார்ப்பு",
  "Refresh": "புதுப்பி",
  "High alert": "உயர் எச்சரிக்கை",
  "Moderate": "மிதமானது",
  "Low": "குறைவு",
  "Field checked: clear": "வயலில் சரிபார்க்கப்பட்டது: பூச்சி இல்லை",
  "Needs recheck": "மீண்டும் சரிபார்க்க வேண்டும்",
  "Not checked": "சரிபார்க்கப்படவில்லை",
  "Latest photo": "சமீபத்திய படம்",
  "View result": "முடிவைப் பார்",
  "Select zone": "மண்டலத்தைத் தேர்ந்தெடு",
  "Colours describe the latest photo, not the whole zone. Green requires a field check; an uncertain photo stays grey.": "நிறங்கள் சமீபத்திய படத்தை மட்டுமே விவரிக்கின்றன, முழு மண்டலத்தையும் அல்ல. பச்சைக்கு வயல் சரிபார்ப்பு தேவை; உறுதியற்ற படம் சாம்பல் நிறத்திலேயே இருக்கும்.",
  "Use a fresh photo of the same plants to track change.": "மாற்றத்தைக் கண்காணிக்க அதே செடிகளின் புதிய படத்தைப் பயன்படுத்தவும்.",
  "Loading zone history…": "மண்டல வரலாறு ஏற்றப்படுகிறது…",
  "Could not load zone history. Please refresh.": "மண்டல வரலாற்றை ஏற்ற முடியவில்லை. புதுப்பிக்கவும்.",
  "History unavailable": "வரலாறு கிடைக்கவில்லை",
  "Pest analysis could not run": "பூச்சி பகுப்பாய்வை இயக்க முடியவில்லை",
  "The pest check could not be completed.": "பூச்சி சரிபார்ப்பை முடிக்க முடியவில்லை.",
  "Check completed and saved to the zone.": "சரிபார்ப்பு முடிந்து மண்டலத்தில் சேமிக்கப்பட்டது.",
  "Scan inconclusive. Please recheck the plant.": "ஸ்கேன் உறுதியற்றது. செடியை மீண்டும் சரிபார்க்கவும்.",
  "Choose a JPG, PNG or WEBP photo.": "JPG, PNG அல்லது WEBP படத்தைத் தேர்ந்தெடுக்கவும்.",
  "Choose a photo smaller than 12 MB.": "12 MB க்குக் குறைவான படத்தைத் தேர்ந்தெடுக்கவும்.",
  "Zone result & plan": "மண்டல முடிவு மற்றும் திட்டம்",
  "Latest test": "சமீபத்திய சோதனை",
  "Earlier test": "முந்தைய சோதனை",
  "Check this zone again": "இந்த மண்டலத்தை மீண்டும் சரிபார்",
  "Close": "மூடு",
  "Detected pest": "கண்டறியப்பட்ட பூச்சி",
  "visible in this photo": "இந்தப் படத்தில் தெரிபவை",
  "photo-level pressure": "படத்தின் அளவிலான பூச்சி அழுத்தம்",
  "Green boxes mark visible pests.": "பச்சைப் பெட்டிகள் தெரியும் பூச்சிகளைக் குறிக்கின்றன.",
  "Photo was not saved for this older test.": "இந்தப் பழைய சோதனைக்குப் படம் சேமிக்கப்படவில்லை.",
  "Saved photo could not be loaded.": "சேமிக்கப்பட்ட படத்தை ஏற்ற முடியவில்லை.",
  "Counts and pressure describe this photo only, not the whole zone.": "எண்ணிக்கையும் அழுத்தமும் இந்தப் படத்தை மட்டுமே விவரிக்கின்றன, முழு மண்டலத்தையும் அல்ல.",
  "No reliable identification from this photo.": "இந்தப் படத்திலிருந்து நம்பகமான அடையாளம் இல்லை.",
  "A pest may still be present. Retake a clear close-up and inspect the plant again.": "பூச்சி இன்னும் இருக்கலாம். தெளிவான அருகிலான படத்தை மீண்டும் எடுத்து செடியை மீண்டும் பரிசோதிக்கவும்.",
  "Farmer checked the plants and reported no visible pests.": "விவசாயி செடிகளைப் பரிசோதித்து, பூச்சிகள் எதுவும் தெரியவில்லை என்று தெரிவித்தார்.",
  "This is a field observation, not a guarantee that the zone is pest-free.": "இது வயல் அவதானிப்பு; மண்டலம் பூச்சியற்றது என்பதற்கான உத்தரவாதம் அல்ல.",
  "I inspected the plants and found no visible pests": "நான் செடிகளைப் பரிசோதித்தேன், பூச்சிகள் எதுவும் தெரியவில்லை",
  "Save field check": "வயல் சரிபார்ப்பைச் சேமி",
  "Field check saved.": "வயல் சரிபார்ப்பு சேமிக்கப்பட்டது.",
  "Could not save field confirmation.": "வயல் உறுதிப்படுத்தலைச் சேமிக்க முடியவில்லை.",
  "Only the latest inconclusive photo can receive a field no-pest confirmation.": "சமீபத்திய உறுதியற்ற படத்திற்கு மட்டுமே வயலில் பூச்சி-இல்லை உறுதிப்படுத்தல் அளிக்க முடியும்.",
  "Photo comparison": "படங்களின் ஒப்பீடு",
  "Previous": "முந்தையது",
  "Now": "இப்போது",
  "Improving in photos": "படங்களில் முன்னேற்றம் தெரிகிறது",
  "Higher pressure in photos": "படங்களில் பூச்சி அழுத்தம் அதிகரித்துள்ளது",
  "Same pressure band": "அழுத்த நிலை அதுவே",
  "First test in this zone": "இந்த மண்டலத்தின் முதல் சோதனை",
  "Different pests — compare separately": "வெவ்வேறு பூச்சிகள் — தனித்தனியே ஒப்பிடவும்",
  "Different crop — no direct comparison": "வேறு பயிர் — நேரடி ஒப்பீடு இல்லை",
  "No reliable comparison yet": "இதுவரை நம்பகமான ஒப்பீடு இல்லை",
  "Photos not confirmed comparable": "படங்கள் ஒப்பிடத்தக்கவை என உறுதிப்படுத்தப்படவில்லை",
  "Field checked — no visible pests": "வயலில் சரிபார்க்கப்பட்டது — பூச்சிகள் எதுவும் தெரியவில்லை",
  "Compare the same plants, angle and distance. Photo counts do not measure whole-field severity.": "அதே செடிகள், கோணம் மற்றும் தொலைவை ஒப்பிடவும். படத்தின் எண்ணிக்கை முழு வயலின் தீவிரத்தை அளவிடாது.",
  "Clear prevention plan": "தெளிவான தடுப்புத் திட்டம்",
  "Do today": "இன்று செய்ய வேண்டியவை",
  "Next 48 hours": "அடுத்த 48 மணி நேரம்",
  "Prevent it returning": "மீண்டும் வராமல் தடுக்கவும்",
  "Treatment & pesticide guidance": "சிகிச்சை மற்றும் பூச்சிக்கொல்லி வழிகாட்டுதல்",
  "Begin with the lowest-impact option. Use a pesticide only after field confirmation and a safe weather check.": "குறைந்த பாதிப்புள்ள வழியில் தொடங்குங்கள். வயல் உறுதிப்படுத்தல் மற்றும் பாதுகாப்பான வானிலைச் சரிபார்ப்புக்குப் பிறகே பூச்சிக்கொல்லியைப் பயன்படுத்துங்கள்.",
  "1. Try lower-impact control first": "1. முதலில் குறைந்த பாதிப்புள்ள கட்டுப்பாட்டை முயற்சிக்கவும்",
  "2. Spray only when all are true": "2. இவை அனைத்தும் உண்மையாக இருந்தால் மட்டுமே தெளிக்கவும்",
  "Pest confirmed:": "பூச்சி உறுதி:",
  "Check nearby plants, not only this photo.": "அருகிலுள்ள செடிகளையும் சரிபார்க்கவும், இந்தப் படத்தை மட்டும் அல்ல.",
  "Action threshold reached:": "நடவடிக்கை வரம்பு எட்டப்பட்டது:",
  "Weather safe:": "வானிலை பாதுகாப்பானது:",
  "No expected rain and no strong wind during application.": "தெளிக்கும்போது மழை எதிர்பார்க்கப்படவில்லை, பலத்த காற்றும் இல்லை.",
  "3. If spraying is necessary": "3. தெளிப்பு அவசியமானால்",
  "Where and when:": "எங்கே, எப்போது:",
  "How much:": "எவ்வளவு:",
  "When to recheck:": "எப்போது மீண்டும் சரிபார்க்க வேண்டும்:",
  "Safety:": "பாதுகாப்பு:",
  "Pre-harvest interval:": "அறுவடைக்கு முந்தைய இடைவெளி:",
  "Confirm the pest and crop with local extension before choosing a pesticide.": "பூச்சிக்கொல்லியைத் தேர்ந்தெடுப்பதற்கு முன் உள்ளூர் வேளாண் விரிவாக்க அலுவலரிடம் பூச்சியையும் பயிரையும் உறுதிப்படுத்துங்கள்.",
  "Listen to advice": "ஆலோசனையைக் கேளுங்கள்",
  "Voice playback is not supported on this device.": "இந்தச் சாதனத்தில் குரல் இயக்கம் ஆதரிக்கப்படவில்லை.",
  "Zone test history": "மண்டல சோதனை வரலாறு",
  "Open any test to view its saved result.": "சேமிக்கப்பட்ட முடிவைக் காண எந்தச் சோதனையையும் திறக்கவும்.",
  "visible": "தெரிபவை",
}
