"use client"

import { useMemo } from "react"
import { useLanguage } from "@/lib/language-context"
import { getPestPhraseMap } from "@/lib/pest-phrase-map"

const hindi: Record<string, string> = {
  "Pressure unknown": "कीट दबाव अज्ञात",
  "Classifier result": "वर्गीकरण मॉडल का नतीजा",
  "Classifier result — location and count unavailable.": "वर्गीकरण का नतीजा — स्थान और गिनती उपलब्ध नहीं हैं।",
  "Pest count and pressure are unavailable. Take a closer photo to measure visible pests.": "कीटों की गिनती और दबाव उपलब्ध नहीं हैं। गिनती के लिए और नज़दीक से फोटो लें।",
  "Do not repeat the same IRAC group or spray from old leaf damage alone.": "एक ही IRAC समूह का बार-बार उपयोग न करें और केवल पुरानी पत्ती की क्षति देखकर छिड़काव न करें।",
  "Rotate IRAC groups and treat new activity, not old deadhearts or whiteheads.": "IRAC समूह बदलते रहें और नई कीट गतिविधि का उपचार करें, केवल पुराने सूखे मध्य अंकुर या सफेद बालियों का नहीं।",
  "Rotate IRAC groups and avoid resurgence-causing calendar applications.": "IRAC समूह बदलते रहें और केवल तय तारीख के अनुसार ऐसे छिड़काव से बचें जिनसे कीट फिर बढ़ सकते हैं।",
  "Rotate IRAC groups and confirm species because planthopper response differs.": "IRAC समूह बदलते रहें और प्रजाति की पुष्टि करें, क्योंकि अलग फुदकों पर उपचार का असर अलग होता है।",
  "Rotate IRAC groups and avoid calendar treatment.": "IRAC समूह बदलते रहें और केवल तय तारीख के अनुसार उपचार न करें।",
  "Rotate IRAC groups and do not treat old bored stems without fresh activity.": "IRAC समूह बदलते रहें और नई कीट गतिविधि के बिना पुराने छेद वाले तनों का उपचार न करें।",
  "Rotate IRAC groups and avoid repeated use of one active ingredient.": "IRAC समूह बदलते रहें और एक ही सक्रिय घटक का बार-बार उपयोग न करें।",
  "Rotate IRAC groups and preserve natural enemies.": "IRAC समूह बदलते रहें और कीटों के प्राकृतिक शत्रुओं को बचाएँ।",
  "Rotate IRAC groups and avoid repeated broad-spectrum sprays.": "IRAC समूह बदलते रहें और बार-बार व्यापक असर वाले छिड़काव से बचें।",
  "Rotate IRAC groups and do not repeat ineffective applications against older larvae.": "IRAC समूह बदलते रहें और बड़ी इल्लियों पर बेअसर उपचार को दोहराएँ नहीं।",
  "Pest map": "कीट मानचित्र",
  "Select a zone, check a photo, then open the zone for its plan and history.": "क्षेत्र चुनें, फोटो जाँचें और योजना व पिछली जाँच देखने के लिए क्षेत्र खोलें।",
  "Pest detector ready": "कीट पहचान मॉडल तैयार है",
  "Pest detector unavailable": "कीट पहचान मॉडल उपलब्ध नहीं है",
  "Checking model…": "मॉडल की जाँच जारी है…",
  "Check a plant": "पौधे की जाँच करें",
  "Take or choose a pest photo": "कीट की फोटो लें या चुनें",
  "Tap to change photo": "फोटो बदलने के लिए दबाएँ",
  "Use one clear close-up. Include the insect and its damage where possible.": "एक साफ नज़दीकी फोटो लें। हो सके तो कीट और उसका नुकसान दोनों दिखाएँ।",
  "Field zone": "खेत का क्षेत्र",
  "Crop": "फसल",
  "Zone": "क्षेत्र",
  "Check this photo": "इस फोटो की जाँच करें",
  "Checking photo…": "फोटो की जाँच जारी है…",
  "Same plants and similar photo distance as the previous test": "पिछली जाँच वाले पौधे और लगभग उतनी ही दूरी से ली गई फोटो",
  "Tick only for comparable photos. Otherwise no improvement claim is made.": "तुलनीय फोटो होने पर ही चुनें। अन्यथा सुधार का दावा नहीं किया जाएगा।",
  "Results save automatically to the selected zone.": "नतीजे चुने गए क्षेत्र में अपने आप सहेजे जाते हैं।",
  "Farm Layout": "खेत का विन्यास",
  "Same farm zones · latest pest check": "खेत के वही क्षेत्र · सबसे नई कीट जाँच",
  "Refresh": "ताज़ा करें",
  "High alert": "उच्च चेतावनी",
  "Moderate": "मध्यम",
  "Low": "कम",
  "Field checked: clear": "खेत में जाँच: कीट नहीं दिखे",
  "Needs recheck": "फिर जाँचें",
  "Not checked": "जाँच नहीं हुई",
  "Latest photo": "सबसे नई फोटो",
  "View result": "नतीजा देखें",
  "Select zone": "क्षेत्र चुनें",
  "Colours describe the latest photo, not the whole zone. Green requires a field check; an uncertain photo stays grey.": "रंग सबसे नई फोटो के नतीजे बताते हैं, पूरे क्षेत्र की स्थिति नहीं। हरे रंग के लिए खेत में जाँच ज़रूरी है; अनिश्चित फोटो धूसर रहती है।",
  "Use a fresh photo of the same plants to track change.": "बदलाव देखने के लिए उन्हीं पौधों की नई फोटो लें।",
  "Loading zone history…": "क्षेत्र की पिछली जाँच लोड हो रही है…",
  "Could not load zone history. Please refresh.": "क्षेत्र की पिछली जाँच लोड नहीं हुई। फिर प्रयास करें।",
  "History unavailable": "पिछली जाँच उपलब्ध नहीं है",
  "Pest analysis could not run": "कीट की जाँच नहीं चल सकी",
  "The pest check could not be completed.": "कीट की जाँच पूरी नहीं हो सकी।",
  "Check completed and saved to the zone.": "जाँच पूरी हुई और क्षेत्र में सहेजी गई।",
  "Scan inconclusive. Please recheck the plant.": "फोटो से पक्की पहचान नहीं हुई। पौधे को फिर जाँचें।",
  "Choose a JPG, PNG or WEBP photo.": "JPG, PNG या WEBP फोटो चुनें।",
  "Choose a photo smaller than 12 MB.": "12 MB से छोटी फोटो चुनें।",
  "Zone result & plan": "क्षेत्र का नतीजा और योजना",
  "Latest test": "सबसे नई जाँच",
  "Earlier test": "पिछली जाँच",
  "Check this zone again": "इस क्षेत्र की फिर जाँच करें",
  "Close": "बंद करें",
  "Detected pest": "पहचाना गया कीट",
  "visible in this photo": "इस फोटो में दिखे",
  "photo-level pressure": "फोटो में कीट दबाव",
  "Green boxes mark visible pests.": "हरे बॉक्स फोटो में दिख रहे कीट बताते हैं।",
  "Photo was not saved for this older test.": "इस पुरानी जाँच की फोटो सहेजी नहीं गई थी।",
  "Saved photo could not be loaded.": "सहेजी गई फोटो लोड नहीं हुई।",
  "Counts and pressure describe this photo only, not the whole zone.": "गिनती और कीट दबाव केवल इस फोटो के हैं, पूरे क्षेत्र के नहीं।",
  "No reliable identification from this photo.": "इस फोटो से भरोसेमंद पहचान नहीं हुई।",
  "A pest may still be present. Retake a clear close-up and inspect the plant again.": "कीट अब भी हो सकते हैं। साफ नज़दीकी फोटो लें और पौधे को फिर जाँचें।",
  "Farmer checked the plants and reported no visible pests.": "किसान ने पौधों की जाँच करके बताया कि कोई कीट नहीं दिखा।",
  "This is a field observation, not a guarantee that the zone is pest-free.": "यह खेत में किया गया निरीक्षण है, पूरे क्षेत्र के कीट-मुक्त होने की गारंटी नहीं।",
  "I inspected the plants and found no visible pests": "मैंने पौधों की जाँच की और कोई कीट नहीं दिखा",
  "Save field check": "खेत की जाँच सहेजें",
  "Field check saved.": "खेत की जाँच सहेज दी गई।",
  "Could not save field confirmation.": "खेत की जाँच सहेजी नहीं जा सकी।",
  "Only the latest inconclusive photo can receive a field no-pest confirmation.": "केवल सबसे नई अनिश्चित फोटो पर खेत की कीट-रहित जाँच सहेजी जा सकती है।",
  "Photo comparison": "फोटो की तुलना",
  "Previous": "पिछली",
  "Now": "अब",
  "Improving in photos": "फोटो में सुधार दिख रहा है",
  "Higher pressure in photos": "फोटो में कीट दबाव बढ़ा है",
  "Same pressure band": "कीट दबाव की श्रेणी समान है",
  "First test in this zone": "इस क्षेत्र की पहली जाँच",
  "Different pests — compare separately": "अलग कीट मिले — अलग तुलना करें",
  "Different crop — no direct comparison": "अलग फसल — सीधी तुलना नहीं",
  "No reliable comparison yet": "अभी भरोसेमंद तुलना नहीं है",
  "Photos not confirmed comparable": "फोटो तुलनीय होने की पुष्टि नहीं है",
  "Field checked — no visible pests": "खेत में जाँच — कोई कीट नहीं दिखा",
  "Compare the same plants, angle and distance. Photo counts do not measure whole-field severity.": "उन्हीं पौधों, कोण और दूरी की तुलना करें। फोटो की गिनती पूरे खेत की गंभीरता नहीं मापती।",
  "Clear prevention plan": "स्पष्ट रोकथाम योजना",
  "Do today": "आज करें",
  "Next 48 hours": "अगले 48 घंटों में",
  "Prevent it returning": "कीट को वापस आने से रोकें",
  "Treatment & pesticide guidance": "उपचार और कीटनाशक मार्गदर्शन",
  "Begin with the lowest-impact option. Use a pesticide only after field confirmation and a safe weather check.": "कम नुकसान वाले उपाय से शुरू करें। खेत में पुष्टि और सुरक्षित मौसम की जाँच के बाद ही कीटनाशक उपयोग करें।",
  "1. Try lower-impact control first": "1. पहले कम नुकसान वाले उपाय करें",
  "2. Spray only when all are true": "2. सभी शर्तें पूरी होने पर ही छिड़कें",
  "Pest confirmed:": "कीट की पुष्टि:",
  "Check nearby plants, not only this photo.": "आस-पास के पौधे जाँचें, केवल यह फोटो नहीं।",
  "Action threshold reached:": "कार्रवाई की सीमा पूरी हो:",
  "Weather safe:": "मौसम सुरक्षित हो:",
  "No expected rain and no strong wind during application.": "छिड़काव के समय बारिश की संभावना या तेज़ हवा न हो।",
  "3. If spraying is necessary": "3. यदि छिड़काव ज़रूरी हो",
  "Where and when:": "कहाँ और कब:",
  "How much:": "कितनी मात्रा:",
  "When to recheck:": "दोबारा कब जाँचें:",
  "Safety:": "सुरक्षा:",
  "Pre-harvest interval:": "कटाई से पहले प्रतीक्षा अवधि:",
  "Confirm the pest and crop with local extension before choosing a pesticide.": "कीटनाशक चुनने से पहले स्थानीय कृषि विशेषज्ञ से कीट और फसल की पुष्टि करें।",
  "Listen to advice": "सलाह सुनें",
  "Voice playback is not supported on this device.": "इस उपकरण पर आवाज़ में सलाह उपलब्ध नहीं है।",
  "Zone test history": "क्षेत्र की पिछली जाँच",
  "Open any test to view its saved result.": "सहेजा गया नतीजा देखने के लिए कोई भी जाँच खोलें।",
  "visible": "दिखे",
}

export function usePestText() {
  const { language } = useLanguage()
  const map = useMemo(() => ({ ...getPestPhraseMap(language), ...(language === "hi" ? hindi : {}) }), [language])
  return { language, text: (value: string) => map[value] ?? value }
}
