/**
 * Marathi overlay for the pest-zone screen. Keyed by the exact English source
 * string used in the component, matching the Hindi overlay's shape.
 * Translated faithfully from the English source; not yet reviewed by a native
 * speaker or an agronomist.
 */
export const pestZoneMarathi: Record<string, string> = {
  "Pressure unknown": "कीड दाब अज्ञात",
  "Classifier result": "वर्गीकरण मॉडेलचा निकाल",
  "Classifier result — location and count unavailable.": "वर्गीकरण मॉडेलचा निकाल — स्थान आणि संख्या उपलब्ध नाही.",
  "Pest count and pressure are unavailable. Take a closer photo to measure visible pests.": "कीडांची संख्या आणि दाब उपलब्ध नाही. मोजण्यासाठी अधिक जवळून फोटो घ्या.",
  "Do not repeat the same IRAC group or spray from old leaf damage alone.": "एकाच IRAC गटाची पुनरावृत्ती करू नका आणि केवळ जुन्या पानांच्या नुकसानीवरून फवारणी करू नका.",
  "Rotate IRAC groups and treat new activity, not old deadhearts or whiteheads.": "IRAC गट बदलत राहा आणि नवीन कीड हालचालीवर उपचार करा, जुन्या वाळलेल्या मध्य फुटव्यांवर किंवा पांढऱ्या ओंब्यांवर नाही.",
  "Rotate IRAC groups and avoid resurgence-causing calendar applications.": "IRAC गट बदलत राहा आणि कीड पुन्हा वाढवणाऱ्या ठरलेल्या तारखेच्या फवारण्या टाळा.",
  "Rotate IRAC groups and confirm species because planthopper response differs.": "IRAC गट बदलत राहा आणि प्रजाती निश्चित करा, कारण तुडतुड्यांचा प्रतिसाद वेगळा असतो.",
  "Rotate IRAC groups and avoid calendar treatment.": "IRAC गट बदलत राहा आणि ठरलेल्या तारखेनुसार उपचार टाळा.",
  "Rotate IRAC groups and do not treat old bored stems without fresh activity.": "IRAC गट बदलत राहा आणि नवीन कीड हालचालीशिवाय जुन्या छिद्रे पडलेल्या खोडांवर उपचार करू नका.",
  "Rotate IRAC groups and avoid repeated use of one active ingredient.": "IRAC गट बदलत राहा आणि एकाच सक्रिय घटकाचा वारंवार वापर टाळा.",
  "Rotate IRAC groups and preserve natural enemies.": "IRAC गट बदलत राहा आणि नैसर्गिक शत्रू कीटक जपा.",
  "Rotate IRAC groups and avoid repeated broad-spectrum sprays.": "IRAC गट बदलत राहा आणि व्यापक परिणाम करणाऱ्या फवारण्यांची पुनरावृत्ती टाळा.",
  "Rotate IRAC groups and do not repeat ineffective applications against older larvae.": "IRAC गट बदलत राहा आणि मोठ्या अळ्यांवर निष्प्रभ ठरलेले उपचार पुन्हा करू नका.",
  "Pest map": "कीड नकाशा",
  "Select a zone, check a photo, then open the zone for its plan and history.": "झोन निवडा, फोटो तपासा, नंतर योजना आणि इतिहास पाहण्यासाठी झोन उघडा.",
  "Pest detector ready": "कीड शोधक तयार आहे",
  "Pest detector unavailable": "कीड शोधक उपलब्ध नाही",
  "Checking model…": "मॉडेल तपासले जात आहे…",
  "Check a plant": "एक रोप तपासा",
  "Take or choose a pest photo": "कीडेचा फोटो घ्या किंवा निवडा",
  "Tap to change photo": "फोटो बदलण्यासाठी टॅप करा",
  "Use one clear close-up. Include the insect and its damage where possible.": "एक स्पष्ट जवळचा फोटो वापरा. शक्य असल्यास कीड आणि तिचे नुकसान दोन्ही समाविष्ट करा.",
  "Field zone": "शेत झोन",
  "Crop": "पीक",
  "Zone": "झोन",
  "Check this photo": "हा फोटो तपासा",
  "Checking photo…": "फोटो तपासला जात आहे…",
  "Same plants and similar photo distance as the previous test": "मागील तपासणीसारखीच रोपे आणि तेवढेच फोटो अंतर",
  "Tick only for comparable photos. Otherwise no improvement claim is made.": "फक्त तुलनायोग्य फोटोंसाठीच खूण करा. अन्यथा सुधारणेचा दावा केला जात नाही.",
  "Results save automatically to the selected zone.": "निकाल निवडलेल्या झोनमध्ये आपोआप जतन होतात.",
  "Farm Layout": "शेत मांडणी",
  "Same farm zones · latest pest check": "तेच शेत झोन · अलीकडील कीड तपासणी",
  "Refresh": "रीफ्रेश",
  "High alert": "उच्च इशारा",
  "Moderate": "मध्यम",
  "Low": "कमी",
  "Field checked: clear": "शेतात तपासले: कीड नाही",
  "Needs recheck": "पुन्हा तपासणी आवश्यक",
  "Not checked": "तपासले नाही",
  "Latest photo": "अलीकडील फोटो",
  "View result": "निकाल पहा",
  "Select zone": "झोन निवडा",
  "Colours describe the latest photo, not the whole zone. Green requires a field check; an uncertain photo stays grey.": "रंग अलीकडील फोटोचे वर्णन करतात, संपूर्ण झोनचे नाही. हिरव्यासाठी शेतात तपासणी आवश्यक आहे; अनिश्चित फोटो करडा राहतो.",
  "Use a fresh photo of the same plants to track change.": "बदल पाहण्यासाठी त्याच रोपांचा नवीन फोटो वापरा.",
  "Loading zone history…": "झोन इतिहास लोड होत आहे…",
  "Could not load zone history. Please refresh.": "झोन इतिहास लोड करता आला नाही. कृपया रीफ्रेश करा.",
  "History unavailable": "इतिहास उपलब्ध नाही",
  "Pest analysis could not run": "कीड विश्लेषण चालू शकले नाही",
  "The pest check could not be completed.": "कीड तपासणी पूर्ण होऊ शकली नाही.",
  "Check completed and saved to the zone.": "तपासणी पूर्ण झाली आणि झोनमध्ये जतन केली.",
  "Scan inconclusive. Please recheck the plant.": "स्कॅन अनिर्णायक. कृपया रोप पुन्हा तपासा.",
  "Choose a JPG, PNG or WEBP photo.": "JPG, PNG किंवा WEBP फोटो निवडा.",
  "Choose a photo smaller than 12 MB.": "12 MB पेक्षा लहान फोटो निवडा.",
  "Zone result & plan": "झोन निकाल व योजना",
  "Latest test": "अलीकडील तपासणी",
  "Earlier test": "पूर्वीची तपासणी",
  "Check this zone again": "हा झोन पुन्हा तपासा",
  "Close": "बंद करा",
  "Detected pest": "आढळलेली कीड",
  "visible in this photo": "या फोटोत दिसणारे",
  "photo-level pressure": "फोटो-पातळीवरील कीड दाब",
  "Green boxes mark visible pests.": "हिरवे चौकोन दिसणाऱ्या कीड दर्शवतात.",
  "Photo was not saved for this older test.": "या जुन्या तपासणीसाठी फोटो जतन केला नव्हता.",
  "Saved photo could not be loaded.": "जतन केलेला फोटो लोड करता आला नाही.",
  "Counts and pressure describe this photo only, not the whole zone.": "संख्या आणि कीड दाब फक्त या फोटोचे वर्णन करतात, संपूर्ण झोनचे नाही.",
  "No reliable identification from this photo.": "या फोटोवरून विश्वासार्ह ओळख झाली नाही.",
  "A pest may still be present. Retake a clear close-up and inspect the plant again.": "कीड अजूनही असू शकते. स्पष्ट जवळचा फोटो पुन्हा घ्या आणि रोप पुन्हा तपासा.",
  "Farmer checked the plants and reported no visible pests.": "शेतकऱ्याने रोपे तपासली आणि कोणतीही कीड दिसली नाही असे नोंदवले.",
  "This is a field observation, not a guarantee that the zone is pest-free.": "हे शेतातील निरीक्षण आहे, झोन कीडमुक्त असल्याची हमी नाही.",
  "I inspected the plants and found no visible pests": "मी रोपे तपासली आणि कोणतीही कीड दिसली नाही",
  "Save field check": "शेत तपासणी जतन करा",
  "Field check saved.": "शेत तपासणी जतन केली.",
  "Could not save field confirmation.": "शेत खात्री जतन करता आली नाही.",
  "Only the latest inconclusive photo can receive a field no-pest confirmation.": "फक्त अलीकडील अनिर्णायक फोटोलाच शेतातील कीड-नाही खात्री देता येते.",
  "Photo comparison": "फोटो तुलना",
  "Previous": "मागील",
  "Now": "आता",
  "Improving in photos": "फोटोंमध्ये सुधारणा दिसते",
  "Higher pressure in photos": "फोटोंमध्ये कीड दाब वाढला आहे",
  "Same pressure band": "कीड दाब श्रेणी तीच आहे",
  "First test in this zone": "या झोनमधील पहिली तपासणी",
  "Different pests — compare separately": "वेगळ्या कीड — स्वतंत्रपणे तुलना करा",
  "Different crop — no direct comparison": "वेगळे पीक — थेट तुलना नाही",
  "No reliable comparison yet": "अद्याप विश्वासार्ह तुलना नाही",
  "Photos not confirmed comparable": "फोटो तुलनायोग्य असल्याची खात्री नाही",
  "Field checked — no visible pests": "शेतात तपासले — कोणतीही कीड दिसली नाही",
  "Compare the same plants, angle and distance. Photo counts do not measure whole-field severity.": "तीच रोपे, कोन आणि अंतर यांची तुलना करा. फोटोतील संख्या संपूर्ण शेताची तीव्रता मोजत नाही.",
  "Clear prevention plan": "स्पष्ट प्रतिबंध योजना",
  "Do today": "आज करा",
  "Next 48 hours": "पुढील ४८ तास",
  "Prevent it returning": "पुन्हा येण्यापासून रोखा",
  "Treatment & pesticide guidance": "उपचार आणि कीटकनाशक मार्गदर्शन",
  "Begin with the lowest-impact option. Use a pesticide only after field confirmation and a safe weather check.": "सर्वात कमी परिणाम करणाऱ्या पर्यायाने सुरुवात करा. कीटकनाशक फक्त शेतातील खात्री आणि सुरक्षित हवामान तपासणीनंतरच वापरा.",
  "1. Try lower-impact control first": "1. आधी कमी परिणामकारक नियंत्रण वापरून पहा",
  "2. Spray only when all are true": "2. या सर्व गोष्टी खऱ्या असतील तरच फवारणी करा",
  "Pest confirmed:": "कीडेची खात्री:",
  "Check nearby plants, not only this photo.": "जवळची रोपे तपासा, फक्त हा फोटो नाही.",
  "Action threshold reached:": "कृती मर्यादा गाठली:",
  "Weather safe:": "हवामान सुरक्षित:",
  "No expected rain and no strong wind during application.": "फवारणीदरम्यान पावसाची शक्यता नाही आणि जोरदार वारा नाही.",
  "3. If spraying is necessary": "3. फवारणी आवश्यक असल्यास",
  "Where and when:": "कुठे आणि कधी:",
  "How much:": "किती:",
  "When to recheck:": "पुन्हा कधी तपासावे:",
  "Safety:": "सुरक्षा:",
  "Pre-harvest interval:": "काढणीपूर्व अंतर:",
  "Confirm the pest and crop with local extension before choosing a pesticide.": "कीटकनाशक निवडण्यापूर्वी स्थानिक कृषी विस्तार अधिकाऱ्याकडून कीड आणि पिकाची खात्री करा.",
  "Listen to advice": "सल्ला ऐका",
  "Voice playback is not supported on this device.": "या उपकरणावर आवाज प्लेबॅक समर्थित नाही.",
  "Zone test history": "झोन तपासणी इतिहास",
  "Open any test to view its saved result.": "जतन केलेला निकाल पाहण्यासाठी कोणतीही तपासणी उघडा.",
  "visible": "दिसणारे",
}
