/**
 * Telugu overlay for the pest-zone screen. Keyed by the exact English source
 * string used in the component, matching the Hindi overlay's shape.
 * Translated faithfully from the English source; not yet reviewed by a native
 * speaker or an agronomist.
 */
export const pestZoneTelugu: Record<string, string> = {
  "Do not repeat the same IRAC group or spray from old leaf damage alone.": "ఒకే IRAC సమూహాన్ని పదే పదే వాడవద్దు; పాత ఆకు నష్టాన్ని మాత్రమే చూసి పిచికారీ చేయవద్దు.",
  "Rotate IRAC groups and treat new activity, not old deadhearts or whiteheads.": "IRAC సమూహాలను మార్చుతూ ఉండండి; పాత ఎండిన మొవ్వులకు లేదా తెల్ల కంకులకు కాకుండా కొత్త పురుగు కదలికకు చికిత్స చేయండి.",
  "Rotate IRAC groups and avoid resurgence-causing calendar applications.": "IRAC సమూహాలను మార్చుతూ ఉండండి; పురుగులు తిరిగి పెరిగేలా చేసే క్యాలెండర్ ఆధారిత పిచికారీలను నివారించండి.",
  "Rotate IRAC groups and confirm species because planthopper response differs.": "IRAC సమూహాలను మార్చుతూ ఉండండి; దోమ పురుగుల స్పందన వేరుగా ఉంటుంది కాబట్టి జాతిని నిర్ధారించండి.",
  "Rotate IRAC groups and avoid calendar treatment.": "IRAC సమూహాలను మార్చుతూ ఉండండి; క్యాలెండర్ ఆధారిత చికిత్సను నివారించండి.",
  "Rotate IRAC groups and do not treat old bored stems without fresh activity.": "IRAC సమూహాలను మార్చుతూ ఉండండి; కొత్త పురుగు కదలిక లేకుండా పాత రంధ్రాలు పడిన కాండాలకు చికిత్స చేయవద్దు.",
  "Rotate IRAC groups and avoid repeated use of one active ingredient.": "IRAC సమూహాలను మార్చుతూ ఉండండి; ఒకే క్రియాశీల పదార్థాన్ని పదే పదే వాడటం నివారించండి.",
  "Rotate IRAC groups and preserve natural enemies.": "IRAC సమూహాలను మార్చుతూ ఉండండి; సహజ శత్రు కీటకాలను కాపాడండి.",
  "Rotate IRAC groups and avoid repeated broad-spectrum sprays.": "IRAC సమూహాలను మార్చుతూ ఉండండి; విస్తృత ప్రభావ పిచికారీలను పదే పదే చేయడం నివారించండి.",
  "Rotate IRAC groups and do not repeat ineffective applications against older larvae.": "IRAC సమూహాలను మార్చుతూ ఉండండి; పెద్ద లార్వాలపై ప్రభావం చూపని చికిత్సలను పునరావృతం చేయవద్దు.",
  "Pest map": "పురుగుల మ్యాప్",
  "Select a zone, check a photo, then open the zone for its plan and history.": "ఒక జోన్‌ను ఎంచుకోండి, ఫోటోను తనిఖీ చేయండి, ఆపై దాని ప్రణాళిక మరియు చరిత్ర కోసం జోన్‌ను తెరవండి.",
  "Pest detector ready": "పురుగు గుర్తింపు సిద్ధం",
  "Pest detector unavailable": "పురుగు గుర్తింపు అందుబాటులో లేదు",
  "Checking model…": "మోడల్ తనిఖీ జరుగుతోంది…",
  "Check a plant": "ఒక మొక్కను తనిఖీ చేయండి",
  "Take or choose a pest photo": "పురుగు ఫోటో తీయండి లేదా ఎంచుకోండి",
  "Tap to change photo": "ఫోటో మార్చడానికి నొక్కండి",
  "Use one clear close-up. Include the insect and its damage where possible.": "ఒక స్పష్టమైన దగ్గరి ఫోటోను ఉపయోగించండి. వీలైతే పురుగు మరియు దాని నష్టం రెండింటినీ చేర్చండి.",
  "Field zone": "క్షేత్ర జోన్",
  "Crop": "పంట",
  "Zone": "జోన్",
  "Check this photo": "ఈ ఫోటోను తనిఖీ చేయండి",
  "Checking photo…": "ఫోటో తనిఖీ జరుగుతోంది…",
  "Same plants and similar photo distance as the previous test": "మునుపటి పరీక్షలోని అవే మొక్కలు మరియు దాదాపు అదే ఫోటో దూరం",
  "Tick only for comparable photos. Otherwise no improvement claim is made.": "పోల్చదగిన ఫోటోలకు మాత్రమే టిక్ చేయండి. లేకపోతే మెరుగుదల గురించి ఎటువంటి వాదన చేయబడదు.",
  "Results save automatically to the selected zone.": "ఫలితాలు ఎంచుకున్న జోన్‌లో స్వయంచాలకంగా భద్రపరచబడతాయి.",
  "Farm Layout": "ఫార్మ్ లేఅవుట్",
  "Same farm zones · latest pest check": "అవే ఫార్మ్ జోన్‌లు · తాజా పురుగు తనిఖీ",
  "Refresh": "రిఫ్రెష్",
  "High alert": "అధిక హెచ్చరిక",
  "Moderate": "మధ్యస్థం",
  "Low": "తక్కువ",
  "Field checked: clear": "క్షేత్రంలో తనిఖీ: పురుగులు లేవు",
  "Needs recheck": "మళ్లీ తనిఖీ అవసరం",
  "Not checked": "తనిఖీ చేయలేదు",
  "Latest photo": "తాజా ఫోటో",
  "View result": "ఫలితాన్ని చూడండి",
  "Select zone": "జోన్‌ను ఎంచుకోండి",
  "Colours describe the latest photo, not the whole zone. Green requires a field check; an uncertain photo stays grey.": "రంగులు తాజా ఫోటోను మాత్రమే సూచిస్తాయి, మొత్తం జోన్‌ను కాదు. ఆకుపచ్చ కోసం క్షేత్ర తనిఖీ అవసరం; అనిశ్చిత ఫోటో బూడిద రంగులోనే ఉంటుంది.",
  "Use a fresh photo of the same plants to track change.": "మార్పును గమనించడానికి అవే మొక్కల కొత్త ఫోటోను ఉపయోగించండి.",
  "Loading zone history…": "జోన్ చరిత్ర లోడ్ అవుతోంది…",
  "Could not load zone history. Please refresh.": "జోన్ చరిత్రను లోడ్ చేయలేకపోయాం. దయచేసి రిఫ్రెష్ చేయండి.",
  "History unavailable": "చరిత్ర అందుబాటులో లేదు",
  "Pest analysis could not run": "పురుగు విశ్లేషణ నడవలేదు",
  "The pest check could not be completed.": "పురుగు తనిఖీ పూర్తి కాలేదు.",
  "Check completed and saved to the zone.": "తనిఖీ పూర్తయి జోన్‌లో భద్రపరచబడింది.",
  "Scan inconclusive. Please recheck the plant.": "స్కాన్ అనిశ్చితం. దయచేసి మొక్కను మళ్లీ తనిఖీ చేయండి.",
  "Choose a JPG, PNG or WEBP photo.": "JPG, PNG లేదా WEBP ఫోటోను ఎంచుకోండి.",
  "Choose a photo smaller than 12 MB.": "12 MB కంటే చిన్న ఫోటోను ఎంచుకోండి.",
  "Zone result & plan": "జోన్ ఫలితం మరియు ప్రణాళిక",
  "Latest test": "తాజా పరీక్ష",
  "Earlier test": "మునుపటి పరీక్ష",
  "Check this zone again": "ఈ జోన్‌ను మళ్లీ తనిఖీ చేయండి",
  "Close": "మూసివేయండి",
  "Detected pest": "గుర్తించిన పురుగు",
  "visible in this photo": "ఈ ఫోటోలో కనిపిస్తున్నవి",
  "photo-level pressure": "ఫోటో స్థాయి పురుగు ఒత్తిడి",
  "Green boxes mark visible pests.": "ఆకుపచ్చ పెట్టెలు కనిపించే పురుగులను సూచిస్తాయి.",
  "Photo was not saved for this older test.": "ఈ పాత పరీక్ష కోసం ఫోటో భద్రపరచబడలేదు.",
  "Saved photo could not be loaded.": "భద్రపరచిన ఫోటోను లోడ్ చేయలేకపోయాం.",
  "Counts and pressure describe this photo only, not the whole zone.": "లెక్కలు మరియు ఒత్తిడి ఈ ఫోటోను మాత్రమే సూచిస్తాయి, మొత్తం జోన్‌ను కాదు.",
  "No reliable identification from this photo.": "ఈ ఫోటో నుండి నమ్మదగిన గుర్తింపు లేదు.",
  "A pest may still be present. Retake a clear close-up and inspect the plant again.": "పురుగు ఇంకా ఉండవచ్చు. స్పష్టమైన దగ్గరి ఫోటోను మళ్లీ తీసి మొక్కను మళ్లీ పరిశీలించండి.",
  "Farmer checked the plants and reported no visible pests.": "రైతు మొక్కలను పరిశీలించి, ఎటువంటి పురుగులు కనిపించలేదని నివేదించారు.",
  "This is a field observation, not a guarantee that the zone is pest-free.": "ఇది క్షేత్ర పరిశీలన; జోన్ పురుగు రహితమని హామీ కాదు.",
  "I inspected the plants and found no visible pests": "నేను మొక్కలను పరిశీలించాను, ఎటువంటి పురుగులు కనిపించలేదు",
  "Save field check": "క్షేత్ర తనిఖీని భద్రపరచండి",
  "Field check saved.": "క్షేత్ర తనిఖీ భద్రపరచబడింది.",
  "Could not save field confirmation.": "క్షేత్ర నిర్ధారణను భద్రపరచలేకపోయాం.",
  "Only the latest inconclusive photo can receive a field no-pest confirmation.": "తాజా అనిశ్చిత ఫోటోకు మాత్రమే క్షేత్రంలో పురుగు-లేదు నిర్ధారణ ఇవ్వగలం.",
  "Photo comparison": "ఫోటోల పోలిక",
  "Previous": "మునుపటిది",
  "Now": "ఇప్పుడు",
  "Improving in photos": "ఫోటోలలో మెరుగుదల కనిపిస్తోంది",
  "Higher pressure in photos": "ఫోటోలలో పురుగు ఒత్తిడి పెరిగింది",
  "Same pressure band": "ఒత్తిడి శ్రేణి అదే",
  "First test in this zone": "ఈ జోన్‌లో మొదటి పరీక్ష",
  "Different pests — compare separately": "వేర్వేరు పురుగులు — విడిగా పోల్చండి",
  "Different crop — no direct comparison": "వేరే పంట — ప్రత్యక్ష పోలిక లేదు",
  "No reliable comparison yet": "ఇంకా నమ్మదగిన పోలిక లేదు",
  "Photos not confirmed comparable": "ఫోటోలు పోల్చదగినవని నిర్ధారించబడలేదు",
  "Field checked — no visible pests": "క్షేత్రంలో తనిఖీ — ఎటువంటి పురుగులు కనిపించలేదు",
  "Compare the same plants, angle and distance. Photo counts do not measure whole-field severity.": "అవే మొక్కలు, కోణం మరియు దూరాన్ని పోల్చండి. ఫోటోలోని లెక్కలు మొత్తం క్షేత్ర తీవ్రతను కొలవవు.",
  "Clear prevention plan": "స్పష్టమైన నివారణ ప్రణాళిక",
  "Do today": "ఈరోజు చేయండి",
  "Next 48 hours": "తదుపరి 48 గంటలు",
  "Prevent it returning": "మళ్లీ రాకుండా నివారించండి",
  "Treatment & pesticide guidance": "చికిత్స మరియు పురుగుమందు మార్గదర్శకత్వం",
  "Begin with the lowest-impact option. Use a pesticide only after field confirmation and a safe weather check.": "అతి తక్కువ ప్రభావం ఉన్న ఎంపికతో ప్రారంభించండి. క్షేత్ర నిర్ధారణ మరియు సురక్షిత వాతావరణ తనిఖీ తర్వాతే పురుగుమందును వాడండి.",
  "1. Try lower-impact control first": "1. ముందుగా తక్కువ ప్రభావ నియంత్రణను ప్రయత్నించండి",
  "2. Spray only when all are true": "2. ఇవన్నీ నిజమైనప్పుడే స్ప్రే చేయండి",
  "Pest confirmed:": "పురుగు నిర్ధారించబడింది:",
  "Check nearby plants, not only this photo.": "సమీప మొక్కలను తనిఖీ చేయండి, ఈ ఫోటో మాత్రమే కాదు.",
  "Action threshold reached:": "చర్య పరిమితి చేరుకుంది:",
  "Weather safe:": "వాతావరణం సురక్షితం:",
  "No expected rain and no strong wind during application.": "పిచికారీ సమయంలో వర్షం అంచనా లేదు, బలమైన గాలి లేదు.",
  "3. If spraying is necessary": "3. స్ప్రే అవసరమైతే",
  "Where and when:": "ఎక్కడ మరియు ఎప్పుడు:",
  "How much:": "ఎంత:",
  "When to recheck:": "మళ్లీ ఎప్పుడు తనిఖీ చేయాలి:",
  "Safety:": "భద్రత:",
  "Pre-harvest interval:": "కోతకు ముందు విరామం:",
  "Confirm the pest and crop with local extension before choosing a pesticide.": "పురుగుమందును ఎంచుకునే ముందు స్థానిక వ్యవసాయ విస్తరణ అధికారితో పురుగు మరియు పంటను నిర్ధారించుకోండి.",
  "Listen to advice": "సలహా వినండి",
  "Voice playback is not supported on this device.": "ఈ పరికరంలో వాయిస్ ప్లేబ్యాక్ మద్దతు లేదు.",
  "Zone test history": "జోన్ పరీక్ష చరిత్ర",
  "Open any test to view its saved result.": "భద్రపరచిన ఫలితాన్ని చూడటానికి ఏదైనా పరీక్షను తెరవండి.",
  "visible": "కనిపిస్తున్నవి",
}
